var Notifications = Notifications || {};

Notifications.data = {
    APPLICATION_DATA_CHANGE: "data.APPLICATION_DATA_CHANGE"
};

Notifications.ui = {
    INSTANCE_CLICKED: "ui.INSTANCE_CLICKED",
    APPLICATION_CLICKED: "ui.APPLICATION_CLICKED",
    APPLICATION_EXPANSION_STARTED: "ui.APPLICATION_EXPANSION_STARTED",
    APPLICATION_REDUCTION_STARTED: "ui.APPLICATION_REDUCTION_STARTED",
    APPLICATION_EXPANSION_FINISHED: "ui.APPLICATION_EXPANSION_FINISHED",
    APPLICATION_REDUCTION_FINISHED: "ui.APPLICATION_REDUCTION_FINISHED",
};