# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: nutella-framework 0.1.0 ruby lib

Gem::Specification.new do |s|
  s.name = "nutella-framework"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Alessandro Gnoli"]
  s.date = "2014-08-18"
  s.description = "Nutella is a framework to help developers deal with Internet-of-things-like learning applications"
  s.email = "tebemis@gmail.com"
  s.executables = ["nutella"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    ".travis.yml",
    "Gemfile",
    "LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "bin/nutella",
    "lib/nutella-cli/command.rb",
    "lib/nutella-cli/commands/broker.rb",
    "lib/nutella-cli/commands/checkup.rb",
    "lib/nutella-cli/commands/debug.rb",
    "lib/nutella-cli/commands/help.rb",
    "lib/nutella-cli/commands/install.rb",
    "lib/nutella-cli/commands/new.rb",
    "lib/nutella-cli/commands/runs.rb",
    "lib/nutella-cli/commands/start.rb",
    "lib/nutella-cli/commands/stop.rb",
    "lib/nutella-cli/nutella-cli.rb",
    "lib/nutella-cli/tmux/tmux.rb",
    "lib/nutella-config/config.rb",
    "lib/nutella-config/nutella_config_store.rb",
    "lib/nutella-config/runlist.rb",
    "lib/nutella.rb",
    "test/helper.rb",
    "test/test_nutella.rb"
  ]
  s.homepage = "http://github.com/ltg-uic/nutella"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.2"
  s.summary = "A framework for IoT learning applications"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_dependency(%q<simplecov>, [">= 0"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
    s.add_dependency(%q<simplecov>, [">= 0"])
  end
end

