# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: supervisor.proto for package ''

require 'grpc'
require_relative 'supervisor_pb'

module Supervisor
  class Service

    include GRPC::GenericService

    self.marshal_class_method = :encode
    self.unmarshal_class_method = :decode
    self.service_name = 'Supervisor'

    rpc :StartProcess, StartProcessRequest, StartProcessResponse
  end

  Stub = Service.rpc_stub_class
end
