# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: supervisor.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("supervisor.proto", :syntax => :proto3) do
    add_message "StartProcessRequest" do
      optional :process_name, :string, 1
      optional :process_command, :string, 2
      optional :process_log, :string, 3
    end
    add_message "StartProcessResponse" do
      optional :success, :bool, 1
      optional :process_pid, :string, 2
    end
  end
end

StartProcessRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("StartProcessRequest").msgclass
StartProcessResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("StartProcessResponse").msgclass
