var Notifications = Notifications || {};

Notifications.data = {
    APPLICATION_DATA_CHANGE: "data.APPLICATION_DATA_CHANGE",
    MESSAGE_DATA_CHANGE: "data.MESSAGE_DATA_CHANGE"
};


Notifications.alerts = {
    ALERT_CHANGE: "alerts.ALERT_CHANGE",
    EMAILS_CHANGE: "alerts.EMAILS_CHANGE"
};

Notifications.ui = {
    INSTANCE_CLICKED: "ui.INSTANCE_CLICKED",
    APPLICATION_CLICKED: "ui.APPLICATION_CLICKED",
    APPLICATION_EXPANSION_STARTED: "ui.APPLICATION_EXPANSION_STARTED",
    APPLICATION_REDUCTION_STARTED: "ui.APPLICATION_REDUCTION_STARTED",
    APPLICATION_EXPANSION_FINISHED: "ui.APPLICATION_EXPANSION_FINISHED",
    APPLICATION_REDUCTION_FINISHED: "ui.APPLICATION_REDUCTION_FINISHED",
};